url: "https://carrollonline.uk"
baseurl: "/"
title: "carrollonline"
description: Hughie's writings
favicon: assets/images/favicon.ico
permalink: /:path/:basename:output_ext/404.html:output_ext

markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
    - jekyll-bootstrap-sass
    - jekyll-sitemap

sass:
    sass_dir: _sass
    style: compressed

exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - changelog.md
    - "*.Rmd"
    - notes.txt
