title: hugle
email: contact@hugle.co.uk
description: Close up magic
baseurl: "/"
url: "https://hugle.co.uk"
favicon: assets/favicon.ico
permalink: /:path/:basename:output_ext

markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
    - jekyll-bootstrap-sass

sass:
    sass_dir: _sass
    style: compressed

exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - changelog.md
    - "*.Rmd"
    - notes.txt
