url: "http://carrollonline.uk/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "carrollonline" # the name of your site, e.g. ACME Corp.
description: Hugh Carroll's personal site, portfolio, pix, writings
favicon: assets/images/favicon.ico
permalink: /:path/:basename:output_ext

markdown: kramdown
kramdown:
  parse_block_html: true

plugins:
    - jekyll-bootstrap-sass

sass:
    sass_dir: _sass
    style: compressed

exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - changelog.md
    - "*.Rmd"
    - notes.txt
